openapi: "3.0.0"
info:
  title: Student Routes
  version: 1.0.1
  description: Student Endpoints for form submission, status checking, and resubmission

paths:
  /students/submit:
    post:
      summary: Submit email verification form
      description: Allows a student to submit answers to a form
      security:
        - studentCookie: []
      requestBody:
        description: Form submission object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                formId:
                  type: string
                  format: uuid
                answers:
                  type: array
                  items:
                    type: object
                    properties:
                      questionId:
                        type: string
                        format: uuid
                      response:
                        type: string
              required:
                - formId
                - answers
      responses:
        "200":
          description: Form submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Form submitted successfully"
                  submission:
                    type: object
        "401":
          description: Unauthorized - user not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not authenticated"
        "404":
          description: Form not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "form not found"
        "409":
          description: Conflict - already submitted
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "You have already submitted the form"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Some error occurred"

  /students/status:
    get:
      summary: Get student status
      description: Retrieves only the status of the logged-in student
      security:
        - studentCookie: []
      responses:
        "200":
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [PENDING, APPROVED, REJECTED]
        "401":
          description: Unauthorized - user not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not authenticated"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found"
        "500":
          description: Internal server error

  /students/resubmit:
    put:
      summary: Resubmit a form
      description: Allows a student to resubmit a form with updated answers if status is REJECTED
      security:
        - studentCookie: []
      requestBody:
        description: Updated form submission object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                formId:
                  type: string
                  format: uuid
                answers:
                  type: array
                  items:
                    type: object
                    properties:
                      questionId:
                        type: string
                        format: uuid
                      response:
                        type: string
              required:
                - formId
                - answers
      responses:
        "200":
          description: Form resubmitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Form resubmitted successfully"
                  updatedSubmission:
                    type: object
        "401":
          description: Unauthorized - user not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not authenticated"
        "403":
          description: Forbidden - cannot resubmit unless rejected
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Cannot resubmit. Current status is APPROVED"
        "404":
          description: No previous submission or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No previous submission found"
        "500":
          description: Internal server error

components:
  securitySchemes:
    studentCookie:
      type: apiKey
      in: cookie
      name: userId
      description: Authentication cookie for student identification
