openapi: "3.0.0"
info:
  title: SuperAdmin Routes
  version: 1.0.0
  description: SuperAdmin Endpoints for admin management and system administration

paths:
  /superadmin/createAdmin:
    post:
      summary: Create a new admin
      description: Creates a new admin user (only accessible by super admins)
      security:
        - userCookie: []
      requestBody:
        description: Admin user object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "admin_user"
                email:
                  type: string
                  format: email
                  example: "admin@example.com"
                password:
                  type: string
                  example: "securePassword123"
                firstName:
                  type: string
                  example: "John"
                lastName:
                  type: string
                  example: "Doe"
              required:
                - username
                - email
                - password
      responses:
        '200':
          description: Admin created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Admin created successfully"
                  adminId:
                    type: string
                  admin:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      role:
                        type: string
                        example: "admin"
                      createdAt:
                        type: string
                        format: date-time
        '400':
          description: Bad request - Invalid admin data or user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid admin data or username/email already exists"
        '401':
          description: Unauthorized - Invalid or missing super admin cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
        '403':
          description: Forbidden - User is not a super admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Access denied. Super admin privileges required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to create admin"

  /superadmin/admins:
    get:
      summary: Get all admins
      description: Retrieves a list of all admin users (only accessible by super admins)
      security:
        - userCookie: []
      responses:
        '200':
          description: List of all admins
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    username:
                      type: string
                    email:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    role:
                      type: string
                      example: "admin"
                    isApproved:
                      type: boolean
                    isVerified:
                      type: boolean
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
        '401':
          description: Unauthorized - Invalid or missing super admin cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
        '403':
          description: Forbidden - User is not a super admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Access denied. Super admin privileges required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to retrieve admins"

  /superadmin/deleteAdmin/{id}:
    delete:
      summary: Delete an admin
      description: Deletes an admin user by ID (only accessible by super admins)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Admin user ID to delete
      security:
        - userCookie: []
      responses:
        '200':
          description: Admin deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Admin deleted successfully"
                  deletedAdminId:
                    type: string
        '400':
          description: Bad request - Invalid admin ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid admin ID"
        '401':
          description: Unauthorized - Invalid or missing super admin cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
        '403':
          description: Forbidden - User is not a super admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Access denied. Super admin privileges required"
        '404':
          description: Admin not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Admin not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to delete admin"

components:
  securitySchemes:
    userCookie:
      type: apiKey
      in: cookie
      name: user
      description: Authentication cookie for super admin identification and authorization